### PR TITLE
animation_events example

### PR DESCRIPTION
**Pull request by ylluminarious**
I've made the animation_events example here. Currently, it's throwing this error in Google Chrome: https://gist.github.com/ylluminarious/db3c779845728966930c
I think that the error is coming from somewhere in here: https://github.com/orbitalimpact/opal-phaser-examples/blob/animation_events/examples/animation/animation_events.rb#L21-L26
But I'm not really sure why the error is occurring. Anyone (@andreanastacio @gabrielrios), please feel free to chime in.

### CODE REVIEW

**Comment by ylluminarious** [comment]
Additionally, feel free to chat here about whatever anyone feels about the API at this moment.

**Comment by ylluminarious** [comment]
Just an update on the bug with the example in question, @andreanastacio @gabrielrios:
Apparently, the bug is happening because `loopCount` (https://github.com/orbitalimpact/opal-phaser-examples/blob/animation_events/examples/animation/animation_events.rb#L21) is apparently undefined. I got that from the error console in Firefox.

**Comment by gabrielrios** [comment]
The error console on firefox is the same error above? Can you add that here too?
Oh, have you tried inspect the value of var animation this block is receiving? Maybe you'll need to wrap that into a class

**Comment by ylluminarious** [comment]
Yeah, sorry, here's the error that I got in Firefox: https://gist.github.com/e01cbff2f474b7ee9d7e
What I meant was I figured that the error was coming from `loopCount` because of that error.

**Comment by ylluminarious** [comment]
@gabrielrios Yes, I did inspect the value of the `animation` parameter that the block is receiving. It looks to be the `anim` variable: https://github.com/orbitalimpact/opal-phaser-examples/blob/animation_events/examples/animation/animation_events.rb#L40
This is what the console prints out when I `console.log` the value of `animation` (in Firefox): https://gist.github.com/fd80d998be73bb1ed491

**Comment by ylluminarious** [comment]
@andreanastacio I've already spoken with @gabrielrios about this, but I've found a fix for this bug. Here is the code that works when put into animation_events.rb: https://gist.github.com/ylluminarious/275432e5f0e3363fa0fd

**Comment by ndrluis** [comment]
@ylluminarious do you have tried `animation.to_n.loopCount == 1`? Last week I was stuck working maybe this week I can help you... 

and I saw you are using 4 spaces for indenting, do you have any problem to use 2 spaces?

**Comment by ylluminarious** [comment]
@andreanastacio  I have not yet tried `animation.to_n.loopCount == 1`, but, @gabrielrios explained that the `animation` variable was not getting passed as a Ruby object in this case, because it is getting returned by one of Phaser's native classes. And he also said that we should probably start writing more classes to make it feel more Ruby-like.
And concerning the 4-spaced indentation, I don't really have a problem using 2-spaced indentation if that's what you prefer.
Also, it's no problem that you got tied up with work last week; I got tied up with school, too :P.

**Pull request merged**
